# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000

format = """
[$directory](bold red) $kubernetes $jobs $python$git_branch$git_commit$git_state$helm$status
$character"""

[directory]
truncation_length = 3
disabled = false

[kubernetes]
disabled = false
format = "$symbol[$context](bold green) "

[golang]
disabled = true

[jobs]
number_threshold = 1
symbol_threshold = 1
