local builtin = require('telescope.builtin')
Remap('n', 'gf', builtin.find_files, {}, "Find files in project")
Remap('n', 'ff', builtin.git_files, {}, "Find files in git")
Remap('n', '<leader>b', builtin.buffers, {}, "List open buffers")
Remap('n', '<leader>f', builtin.quickfix, {}, "List quickfix")
Remap('n', '<C-e>', builtin.marks, {}, "Show marks")
Remap('n', '<leader>mc', function() vim.cmd(":delm! | delm 0-9A-Za-z") end, {}, "Clear marks")
Remap('n', '<C-g>', function()
	builtin.live_grep();
end, {}, "Live grep")
Remap("n", "<C-s>", function() builtin.lsp_dynamic_workspace_symbols{ symbols = "class" } end, {}, "Workspace symbols")
Remap("n", "<C-d>", builtin.lsp_document_symbols, {}, "Document symbols")
Remap("n", "<leader>vd", builtin.diagnostics, {}, "Open diagnostics floating window")
