local builtin = require('telescope.builtin')
vim.keymap.set('n', 'gf', builtin.find_files, { desc = "Find files in project" })
vim.keymap.set('n', 'ff', builtin.git_files, { desc = "Find files in git" })
vim.keymap.set('n', '<leader>b', builtin.buffers, { desc = "List open buffers" })
vim.keymap.set('n', '<leader>f', builtin.quickfix, { desc = "List quickfix" })
vim.keymap.set('n', '<C-e>', builtin.marks, { desc = "Show marks" })
vim.keymap.set('n', '<leader>mc', function() vim.cmd(":delm! | delm 0-9A-Za-z") end, { desc = "Clear marks" })
vim.keymap.set('n', '<C-g>', function()
	builtin.live_grep();
end, { desc = "Live grep" })
vim.keymap.set("n", "<C-s>", function() builtin.lsp_dynamic_workspace_symbols{ symbols = "class" } end, { desc = "Workspace symbols" })
vim.keymap.set("n", "<C-d>", builtin.lsp_document_symbols, { desc = "Document symbols" })
vim.keymap.set("n", "<leader>vd", builtin.diagnostics, { desc = "Open diagnostics floating window" })
