# $XDG_CONFIG_HOME/k9s/config.yaml
k9s:
  # Enable periodic refresh of resource browser windows. Default false
  liveViewAutoRefresh: false
  # The path to screen dump. Default: '%temp_dir%/k9s-screens-%username%' (k9s info)
  screenDumpDir: '%temp_dir%/k9s-screens-%username%'
  # Represents ui poll intervals in seconds. Default 2secs
  refreshRate: 2
  # Overrides the default k8s api server requests timeout. Defaults 120s
  apiServerTimeout: 15s
  # Number of retries once the connection to the api-server is lost. Default 15.
  maxConnRetry: 5
  # Indicates whether modification commands like delete/kill/edit are disabled. Default is false
  readOnly: false
  # This setting allows users to specify the default view, but it is not set by default.
  defaultView: ""
  # Toggles whether k9s should exit when CTRL-C is pressed. When set to true, you will need to exit k9s via the :quit command. Default is false.
  noExitOnCtrlC: false
  #UI settings
  ui:
    # Enable mouse support. Default false
    enableMouse: false
    # Set to true to hide K9s header. Default false
    headless: false
    # Set to true to hide the K9S logo Default false
    logoless: false
    # Set to true to hide K9s crumbs. Default false
    crumbsless: false
    # Set to true to suppress the K9s splash screen on start. Default false. Note that for larger clusters or higher latency connections, there may be no resources visible initially until local caches have finished populating.
    splashless: false
    # Toggles icons display as not all terminal support these chars. Default: true
    noIcons: false
    # Toggles reactive UI. This option provide for watching on disk artifacts changes and update the UI live Defaults to false.
    reactive: false
    # By default all contexts will use the dracula skin unless explicitly overridden in the context config file.
    skin: dracula # => assumes the file skins/dracula.yaml is present in the  $XDG_DATA_HOME/k9s/skins directory
    # Allows to set certain views default fullscreen mode. (yaml, helm history, describe, value_extender, details, logs) Default false
    defaultsToFullScreen: false
    # Show full resource GVR (Group/Version/Resource) vs just R. Default: false.
    useFullGVRTitle: false
  # Toggles icons display as not all terminal support these chars.
  noIcons: false
  # Toggles whether k9s should check for the latest revision from the GitHub repository releases. Default is false.
  skipLatestRevCheck: false
  # When altering kubeconfig or using multiple kube configs, k9s will clean up clusters configurations that are no longer in use. Setting this flag to true will keep k9s from cleaning up inactive cluster configs. Defaults to false.
  keepMissingClusters: false
  # Logs configuration
  logger:
    # Defines the number of lines to return. Default 100
    tail: 500
    # Defines the total number of log lines to allow in the view. Default 1000
    buffer: 1000
    # Represents how far to go back in the log timeline in seconds. Setting to -1 will tail logs. Default is -1.
    sinceSeconds: -1 # => tail the last 5 mins.
    # Toggles log line wrap. Default false
    textWrap: true
    # Autoscroll in logs will be disabled. Default is false.
    disableAutoscroll: false
    # Toggles log line timestamp info. Default false
    showTime: true
